print("Here the input data will be created with MADRAT and copied to the model")
library(mrprom)
dev <- unclass(Sys.time())
fname <- paste0("rev0",dev,"_28b9ea46_open_prom.tgz")
retrieveData("OPEN_PROM",puc=F,renv=F,regionmapping = "regionmappingOP.csv",dev=dev)
file.copy(paste0(getConfig("outputfolder"),"/",fname),fname)
utils::untar(fname)