*' @title Agriculture module Preloop
*' @code

*'                *VARIABLE INITIALISATION*
V12EnergyService.LO(runCy,AGRI_MODES,YTIME) = 0;
V12EnergyService.L(runCy,AGRI_MODES,YTIME) = i12DataEnergyService(runCy,AGRI_MODES,"%fBaseY%");
V12EnergyService.FX(runCy,AGRI_MODES,YTIME)$DATAY(YTIME) = i12DataEnergyService(runCy,AGRI_MODES,YTIME);
*---
V12Activity.LO(runCy,AGRI_MODES,YTIME) = 0;
V12Activity.FX(runCy,AGRI_MODES,YTIME)$DATAY(YTIME) = 1;
*---
V12ConsFuel.LO(runCy,AGRI_MODES,EFS,YTIME) = 0;
V12ConsFuel.L(runCy,AGRI_MODES,EFS,YTIME) = i12ConsFuel(runCy,AGRI_MODES,EFS,"%fBaseY%");
V12ConsFuel.FX(runCy,AGRI_MODES,EFS,YTIME)$DATAY(YTIME) = i12ConsFuel(runCy,AGRI_MODES,EFS,YTIME);
*---
V12GapCapacity.LO(runCy,AGRI_MODES,YTIME) = 0;
*---
V12ShareTech.LO(runCy,AGRI_MODES,AGRITECH,YTIME) = 0;
V12ShareTech.UP(runCy,AGRI_MODES,AGRITECH,YTIME) = 1;
*---
V12Capacity.LO(runCy,AGRI_MODES,AGRITECH,YTIME) = 0;
V12Capacity.FX(runCy,AGRI_MODES,AGRITECH,YTIME)$(DATAY(YTIME) and AGRMODEStoTECH(AGRI_MODES,AGRITECH)) =
(
  SUM(EFS$AGRITECHTOEF(AGRITECH,EFS), (i12ConsFuel(runCy,AGRI_MODES,EFS,YTIME) + 1e-6) / i12SpecificFuelCons(runCy,AGRI_MODES,AGRITECH,EFS,YTIME)) /
  SUM((EFS,AGRITECH2)$(AGRITECHTOEF(AGRITECH2,EFS) and AGRMODEStoTECH(AGRI_MODES,AGRITECH2)), (i12ConsFuel(runCy,AGRI_MODES,EFS,YTIME) + 1e-6) / i12SpecificFuelCons(runCy,AGRI_MODES,AGRITECH2,EFS,YTIME)) 
) * i12DataEnergyService(runCy,AGRI_MODES,YTIME);
V12Capacity.FX(runCy,AGRI_MODES,AGRITECH,YTIME)$(not AGRMODEStoTECH(AGRI_MODES,AGRITECH)) = 0;
*---
V12CostFuel.LO(runCy,AGRI_MODES,AGRITECH,YTIME) = 0;
V12CostFuel.L(runCy,AGRI_MODES,AGRITECH,YTIME) = 1;
V12CostFuel.FX(runCy,AGRI_MODES,AGRITECH,YTIME)$(DATAY(YTIME) and AGRMODEStoTECH(AGRI_MODES,AGRITECH)) =
sum(EFS$AGRITECHTOEF(AGRITECH,EFS), 
    VmPriceFuelSubsecCarVal.L(runCy,"AG",EFS,YTIME) * 
    i12SpecificFuelCons(runCy,AGRI_MODES,AGRITECH,EFS,YTIME)
) + 1e-6;
V12CostFuel.FX(runCy,AGRI_MODES,AGRITECH,YTIME)$(not AGRMODEStoTECH(AGRI_MODES,AGRITECH)) = 0;
*---
V12CostTotal.LO(runCy,AGRI_MODES,AGRITECH,YTIME) = 0;
V12CostTotal.L(runCy,AGRI_MODES,AGRITECH,YTIME) = 1;
V12CostTotal.FX(runCy,AGRI_MODES,AGRITECH,YTIME)$(DATAY(YTIME) and AGRMODEStoTECH(AGRI_MODES,AGRITECH)) = V12CostFuel.L(runCy,AGRI_MODES,AGRITECH,YTIME) + 1e-6;
V12CostTotal.FX(runCy,AGRI_MODES,AGRITECH,YTIME)$(not AGRMODEStoTECH(AGRI_MODES,AGRITECH)) = 0;
*---