*' @title Agriculture Sets
*' @code

sets

*---
FOOD_TYPES       Food types /PLANT,MEAT,FISH/
AGRI_MODES       Agriculture energy services  /CROPS,ENERGY_CROPS,IRRIGATION,CLIMATE,POSTHARVESTING,LIVESTOCK,FORESTRY,FISHING/
FERT_TYPES       Fertilizer types /N,P,K/

MODEStoFOOD(AGRI_MODES,FOOD_TYPES)      "Agriculture modes mapped to the corresponding food type production"
/
CROPS.PLANT
LIVESTOCK.MEAT
FISHING.FISH
/

AGRITECH(TTECH)
/
TELC
TGDO
/

AGRMODEStoTECH(AGRI_MODES,AGRITECH)
/
CROPS.TGDO
LIVESTOCK.TELC
IRRIGATION.(TGDO,TELC)
FORESTRY.TGDO
FISHING.TGDO
/

AGRITECHTOEF(AGRITECH,EF)
/
TELC.ELC
TGDO.GDO
/
;

alias(AGRITECH, AGRITECH2);
