*' @title Agriculture Sets
*' @code

sets

*---
FOOD_TYPES       Food types /PLANT,MEAT,FISH/
AGRI_MODES       Agriculture energy services  /CROPS,ENERGY_CROPS,IRRIGATION,CLIMATE,POSTHARVESTING,LIVESTOCK,FORESTRY,FISHING/
FERT_TYPES       Fertilizer types /N,P,K/

MODEStoFOOD(AGRI_MODES,FOOD_TYPES)      "Agriculture modes mapped to the corresponding food type production"
/
CROPS.PLANT
LIVESTOCK.MEAT
FISHING.FISH
/

AGRITECH(TECH)
/
TELC
TGDO
TGSL
TNGS
THCL
TBMSWAS
TRFO
TLPG
TLGN
/

AGRMODEStoTECH(AGRI_MODES,AGRITECH)
/
CROPS.(TGDO,TELC)
LIVESTOCK.TELC
IRRIGATION.(TGDO,TELC,TGSL,THCL,TNGS,TBMSWAS,TLPG,TLGN,TRFO)
CLIMATE.(TNGS,THCL,TBMSWAS,TELC,TLPG,TLGN,TRFO)
FORESTRY.(TGDO,TELC)
FISHING.(TGDO,TRFO,TELC,TLPG,THCL,TLGN,TNGS)
POSTHARVESTING.(TGDO,TELC)
/

AGRITECHTOEF(AGRITECH,EF)
/
TELC.ELC
TGDO.(GDO,BGDO)
TGSL.(GSL,BGSL)
THCL.HCL
TNGS.(NGS,BGAS)
TBMSWAS.BMSWAS
TLPG.LPG
/
;

alias(AGRITECH, AGRITECH2);
