*' @title Agriculture Sets
*' @code

sets

*---
FOOD_TYPES       Food types /PLANT,MEAT,FISH/
AGRI_MODES       "Agriculture energy services" 
/
CROPS             "Food crops"
ENERGY_CROPS      "Energy crops"
IRRIGATION        "Irrigation & Water management"
CLIMATE           "Greenhouses & Climate control"
POSTHARVESTING    "Post-harvesting processes"
LIVESTOCK         "Livestock processes"
FORESTRY          "Forestry"
FISHING           "Fishing"
/
FERT_TYPES       Fertilizer types /N,P,K/

MODEStoFOOD(AGRI_MODES,FOOD_TYPES)      "Agriculture modes mapped to the corresponding food type production"
/
CROPS.PLANT
LIVESTOCK.MEAT
FISHING.FISH
/

AGRITECH(TECH)
/
TELC
TGDO
TGSL
TNGS
THCL
TBMSWAS
TRFO
TLPG
TLGN
TSTE
/

AGRMODEStoTECH(AGRI_MODES,AGRITECH)
/
CROPS.(TGDO,TELC)
LIVESTOCK.TELC
IRRIGATION.(TGDO,TELC,TGSL,THCL,TNGS,TBMSWAS,TLPG,TLGN,TRFO)
CLIMATE.(TNGS,THCL,TBMSWAS,TELC,TLPG,TLGN,TRFO,TSTE)
FORESTRY.(TGDO,TELC)
FISHING.(TGDO,TRFO,TELC,TLPG,THCL,TLGN,TNGS,TGSL)
POSTHARVESTING.(TGDO,TELC)
/

AGRITECHTOEF(AGRITECH,EF)
/
TELC.ELC
TGDO.(GDO,BGDO)
TGSL.(GSL,BGSL)
THCL.HCL
TNGS.(NGS,BGAS)
TBMSWAS.BMSWAS
TLPG.LPG
TRFO.RFO
TLGN.LGN
TSTE.STE
/

AGRI_MODEStoEF(AGRI_MODES,EF)
;

AGRI_MODEStoEF(AGRI_MODES,EF) = yes$SUM(AGRITECH$(AGRMODEStoTECH(AGRI_MODES,AGRITECH) and AGRITECHTOEF(AGRITECH,EF)), 1);
SECtoEF("AG",EF) = yes$SUM(AGRI_MODES$AGRI_MODEStoEF(AGRI_MODES,EF), 1);
alias(AGRITECH, AGRITECH2);
