name: Comment to Issue
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run tdg-github-action
      uses: ribtoks/tdg-github-action@master
      with:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO: ${{ github.repository }}
        SHA: ${{ github.sha }}
        REF: ${{ github.ref }}
        LABEL: "FIXME"
        MIN_WORDS: 1
        MIN_CHARACTERS: 5
        INCLUDE_PATTERN: "\\.(gms|R)$"

permissions:
  issues: write