name: Check file size
on: [push]

jobs:
  file-size-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check large files
        uses: ppremk/lfs-warning@v3.2
        with:
          filesizelimit: 262144 # 256 KB

permissions: read-all