name: 'File Size Checker'
on: [push, pull_request]

jobs:
  check-file-size:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout code'
      uses: actions/checkout@v2
    - name: 'Check file size'
      run: |
        # Set the maximum file size to 256KB
        MAX_SIZE=262144
        
        # List all files in the repository excluding .git directory
        FILES=$(find . -type f ! -path './.git/*')
        
        # Loop through all files and check file size
        for FILE in $FILES; do
          SIZE=$(wc -c <"$FILE")
          if [ "$SIZE" -gt "$MAX_SIZE" ]; then
            echo "Error: $FILE exceeds the maximum file size limit of 256KB."
            exit 1
          fi
        done
        
        echo "All files are within the size limit."

permissions: read-all