name: Test OPEN-PROM Model Run

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-model:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup GAMS
        run: |
          $url = "https://d37drm4t2jghv5.cloudfront.net/distributions/47.1.0/windows/windows_x64_64.exe"
          $installer = "gams_installer.exe"
          Invoke-WebRequest -Uri $url -OutFile $installer
          Start-Process $installer -ArgumentList "/silent" -NoNewWindow -Wait
          Remove-Item $installer
          $env:Path += ";C:\GAMS\47"
          [Environment]::SetEnvironmentVariable("Path", $env:Path, [EnvironmentVariableTarget]::Machine)
          echo $env:Path

      - name: Setup GAMS License
        env:
          LICENSE: ${{ secrets.GAMS_LICENSE }}
          
        run: |
          $licenseFile = "C:\GAMS\47\gamslice.txt"
          New-Item -ItemType Directory -Force -Path "C:\GAMS\47"
          Set-Content -Path $licenseFile -Value $env:LICENSE

      - name: Download Datasets
        env:
          DATASET: ${{ secrets.DATASET }}
        run: |
          @"
          print("Getting data for GitHub Action")
          url <- commandArgs(trailingOnly = TRUE)
          fname <- 'ghaction_data.tgz'
          download.file(url, fname, mode="wb")
          utils::untar(fname, exdir = "./data")
          "@ | Out-File -FilePath dl_data.R

          RScript dl_data.R $env:DATASET
          
      - name: Test Model Run - NPi Default Scenario
        run: |
          & "C:\GAMS\47\gams.exe" main.gms --DevMode=0 --GenerateInput=off --fEndY=2050 --fScenario=1 -Idir=./data

      - name: Test Model Run - 1.5C Scenario
        run: |
          & "C:\GAMS\47\gams.exe" main.gms --DevMode=0 --GenerateInput=off --fEndY=2050 --fScenario=2 -Idir=./data
          
      - name: Test Model Run - 2C Scenario
        run: |
          & "C:\GAMS\47\gams.exe" main.gms --DevMode=0 --GenerateInput=off --fEndY=2050 --fScenario=3 -Idir=./data
