name: Test OPEN-PROM Model Run

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-model:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup GAMS
        run: |
          $url = "https://d37drm4t2jghv5.cloudfront.net/distributions/47.1.0/windows/windows_x64_64.exe"
          $installer = "gams_installer.exe"
          Invoke-WebRequest -Uri $url -OutFile $installer
          Start-Process $installer -ArgumentList "/silent" -NoNewWindow -Wait
          Remove-Item $installer
          $env:Path += ";C:\GAMS\47"
          [Environment]::SetEnvironmentVariable("Path", $env:Path, [EnvironmentVariableTarget]::Machine)
          echo $env:Path

      - name: Setup GAMS License
        env:
          LICENSE: ${{ secrets.GAMS_LICENSE }}
          
        run: |
          $licenseFile = "C:\GAMS\47\gamslice.txt"
          New-Item -ItemType Directory -Force -Path "C:\GAMS\47"
          Set-Content -Path $licenseFile -Value $env:LICENSE

      - name: Download Datasets
        run: |
          @"
          print("Getting data for GitHub Action")
          url <- 'https://drive.usercontent.google.com/uc?id=1Hy0zhnHsouE25O9smP7u75X6l6uU2HIg&export=download'
          fname <- 'ghaction_data.tgz'
          download.file(url, fname, mode="wb")
          utils::untar(fname, exdir = "./data")
          "@ | Out-File -FilePath dl_data.R

          RScript dl_data.R
          
      - name: Test Model Run - NPi Default Scenario
        run: |
          & "C:\GAMS\47\gams.exe" main.gms --DevMode=0 --GenerateInput=off --fEndY=2050 --logOption=0 --logFile=npi.log --fScenario=1 -Idir=./data
      
      - name: Test Model Run - 1.5C Scenario
        run: |
          & "C:\GAMS\47\gams.exe" main.gms --DevMode=0 --GenerateInput=off --fEndY=2050 --logOption=0 --logFile=1p5c.log --fScenario=2 -Idir=./data
          
      - name: Test Model Run - 2C Scenario
        run: |
          & "C:\GAMS\47\gams.exe" main.gms --DevMode=0 --GenerateInput=off --fEndY=2050 --logOption=0 --logFile=2c.log --fScenario=3 -Idir=./data

      - name: Upload GAMS log files
        uses: actions/upload-artifact@v4
        with:
          name: gams-log
          path: |
            npi.log
            1p5c.log
            2c.log
          retention-days: 1